### ISSUE TITLE
Menus don't open + IsLoaded export invalid

### ISSUE THREAD

**Issue by mw-138** [ThymonA/menuv#1]
Using the 'MenuV:OpenMenu' function, it appears that this doesn't open the menu that I have created using the example code found in 'example.lua'. I done some debugging inside the 'menuv.lua' script and found, on line 166, that when the function tries to open the menu, there is an infinite wait loop waiting until 'MenuV.Loaded' is equal to true. But there doesn't seem to be any way of this bool switching to true, ending the loop.

I get an error in my resource when using MenuV that states: 'No such export IsLoaded in resource menuv'
This may be the cause of the problem with 'MenuV.Loaded' not being set to true, however, I am not entirely sure.

**Comment by ThymonA** [comment]
MenuV must be started before all scripts that uses it. What you say about the boolean is also incorrect.

https://github.com/ThymonA/menuv/blob/4c001fb3f62284dd03f473ddffdcdb97998be431/app/menuv.lua#L137-L140

The question is whether you have used a Release version or the current master version?
Because master version has to be compiled manually and when starting FiveM, FiveM does this again.
Problem is not reproducible when correctly installing MenuV or using the latest Release version

**Comment by ThymonA** [comment]
I have added an empty **.yarn.installed** to **master**, this prevents FiveM from retrieving all packages even if you compiled it manually. 

**Commit:** ( ec07d18b20a96439669f3c81616960a7ddf3e0ec ) _Add .yarn.installed, will prevent FiveM from loading all yarn packages_

**Comment by mw-138** [comment]
I was using the master version. I switched to the release version and it works now. Thanks for your help!
